{% set name = "rsconnect-python" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/rsconnect-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: e508b104ba03933546fb4aeb46132fa0f76fbe8c0377b2b6b1885f3e38cba6e2

build:
  noarch: python
  entry_points:
    - rsconnect = rsconnect.main:cli
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python !=2.*,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - six >=1.14.0
    - click >=7.0.0
    - pip >=10.0.0  # rsconnect-python invokes pip as a subprocess
    - semver >=2.0.0,<3.0.0
test:
  imports:
    - rsconnect

about:
  home: https://github.com/rstudio/rsconnect-python
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: The rsconnect-python CLI and library

extra:
  recipe-maintainers:
    - bcwu
    - scottmmjackson
    - dbkegley
