{% set name = "rsconnect-python" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/rsconnect-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: f7f7fc6c57b7d875ea15312d511b07be07c81f93a1253b4778234ac4872ef8c1

build:
  noarch: python
  entry_points:
    - rsconnect = rsconnect.main:cli
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python !=2.*,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,!=3.6.*,!=3.7.*
    - six >=1.14.0
    - click >=8.0.0
    - pip >=10.0.0  # rsconnect-python invokes pip as a subprocess
    - pyjwt >=2.4.0
    - semver >=2.0.0,<3.0.0
test:
  imports:
    - rsconnect

about:
  home: https://github.com/rstudio/rsconnect-python
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: The rsconnect-python CLI and library

extra:
  recipe-maintainers:
    - mmarchetti
    - tdstein
    - dbkegley
