{% set name = "rsconnect-python" %}
{% set version = "1.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/rsconnect-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1b3fec121535ef117b4b7b13cffd192468ff5f55e8e0a56f3f9a3cec3d10204f

build:
  noarch: python
  entry_points:
    - rsconnect = rsconnect.main:cli
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python !=2.*,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - six >=1.14.0
    - click >=7.0.0
    - pip >=10.0.0  # rsconnect-python invokes pip as a subprocess
    - semver >=2.0.0,<3.0.0
test:
  imports:
    - rsconnect

about:
  home: https://github.com/rstudio/rsconnect-python
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: The rsconnect-python CLI and library

extra:
  recipe-maintainers:
    - bcwu
    - scottmmjackson
    - dbkegley
